name: Check that a container builds

on:
  workflow_call:
    inputs:
      dockerfile:
        required: false
        type: string
        default: 'Dockerfile'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2.13
        with:
          dockerfiles: ${{ inputs.dockerfile }}
          image: test
