name: Build Go project

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Build
        run: go build ${INPUTS_PACKAGE}
        env:
          INPUTS_PACKAGE: ${{inputs.package}}
