name: Test Go project

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      tags:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable

      - name: Test
        run: go test -tags "${INPUTS_TAGS}" ${INPUTS_PACKAGE}
        env:
          INPUTS_TAGS: ${{inputs.tags}}
          INPUTS_PACKAGE: ${{inputs.package}}
