name: Test Go project

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      tags:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: stable

      - name: Test
        run: go test -tags "${INPUTS_TAGS}" ${INPUTS_PACKAGE}
        env:
          INPUTS_TAGS: ${{inputs.tags}}
          INPUTS_PACKAGE: ${{inputs.package}}
