name: Test Go project

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'
      tags:
        required: false
        type: string
        default: ''

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Test
        run: go test -tags "${{inputs.tags}}" ${{inputs.package}}
