name: Check Go project for vulnerabilities

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: stable

      - name: Check for vulnerabilities
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest -- "${INPUTS_PACKAGE}"
        env:
          INPUTS_PACKAGE: ${{inputs.package}}
