name: Check Go project for vulnerabilities

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Check for vulnerabilities
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest -- "${INPUTS_PACKAGE}"
        env:
          INPUTS_PACKAGE: ${{inputs.package}}
