name: Check Go project for vulnerabilities

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      package:
        required: false
        type: string
        default: './...'

jobs:
  vulncheck:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Check for vulnerabilities
        run: |
          go run golang.org/x/vuln/cmd/govulncheck@latest -- "${{inputs.package}}"
